version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:

services:

  # Xs2a connector example
  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples
    container_name: xs2a-connector-examples
    restart: on-failure
    ports:
      - "8089:8089"
      - "8189:8000"
    environment:
      - ASPSP_PROFILE_BASEURL=http://xs2a-aspsp-profile:48080/api/v1
      - CONSENT_SERVICE_BASEURL=http://xs2a-consent-management:38080
      - LEDGERS_URL=http://ledgers:8088
      - SPRING_PROFILES_ACTIVE=postgres,mockspi
      - DB_HOST=xs2a_connector_examples_db
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms
    networks:
      - xs2a-net
    depends_on:
      - xs2a-aspsp-profile
      - xs2a-consent-management
      - ledgers

  # Xs2a aspsp profile
  xs2a-aspsp-profile:
    image: adorsys/xs2a-aspsp-profile
    container_name: xs2a-aspsp-profile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx256M"
      - SPRING_PROFILES_ACTIVE=debug_mode
    ports:
      - "48080:8080"
    networks:
      - xs2a-net

  # Consent management
  xs2a-consent-management:
    image: adorsys/xs2a-consent-management
    container_name: xs2a-consent-management
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xs2a-connector-examples-db/consent?currentSchema=consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - ASPSP_PROFILE_BASEURL=http://xs2a-aspsp-profile:48080/api/v1
      - SERVER_KEY=ledgers_conenctor_secret
    depends_on:
      - xs2a-connector-examples-db
      - xs2a-aspsp-profile

  # Xs2a connector example DB
  xs2a-connector-examples-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a_connector_examples_db
    restart: on-failure
    volumes:
      - xs2a-connector-data:/var/lib/pgsql/data
      - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
      - 5432
    ports:
      - "5436:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms

  # Online banking
  xs2a-online-banking:
    image: adorsys/xs2a-online-banking
    container_name: xs2a_online_banking
    restart: on-failure
    build:
      context: online-banking-app
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "8190:8000"
    depends_on:
      - ledgers
      - xs2a-connector-examples
    networks:
      - xs2a-net
    environment:
      - XS2A_URL=http://xs2a-connector-examples:8089
      - LEDGERS_URL=http://ledgers:8088

  # Ledgers
  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    networks:
      - xs2a-net
    ports:
      - "8088:8088"
      - "8188:8000"
    depends_on:
      - xs2a-connector-examples-db
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=xs2a-connector-examples-db
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms