version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:
  ledgers-data:

services:

  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples
    container_name: xs2a-connector-examples
    restart: on-failure
    ports:
    - "8089:8089"
    - "8189:8000"
    environment:
    - LEDGERS_URL=http://ledgers:8088
    - SPRING_PROFILES_ACTIVE=postgres,mockspi
    - DB_HOST=xs2a_connector_examples_db
    - DB_DATABASE=consent
    - DB_USER=cms
    - DB_PASSWORD=cms
    #- DB_SCHEMA=consent
    #- DB_URL=jdbc:postgresql://xs2a_gateway_db:5432/consent?currentSchema=consent
    networks:
    - xs2a-net
    depends_on:
    - xs2a-connector-examples-db
    - ledgers

  xs2a-online-banking:
    image: adorsys/xs2a-online-banking
    container_name: xs2a_online_banking
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-OBA
    ports:
    - "8090:8090"
    - "8190:8000"
    depends_on:
    - ledgers
    - xs2a-gateway
    networks:
    - xs2a-net
    environment:
    - XS2A_URL=http://xs2a_gateway:8089
    - LEDGERS_URL=http://ledgers:8088

  ledgers:
    image: adorsys/ledgers:develop
    container_name: ledgers
    restart: on-failure
    networks:
    - xs2a-net
    ports:
    - "8088:8088"
    - "8188:8000"
    depends_on:
    - ledgers-db
    environment:
    - DB_HOST=ledgers_db
    - SPRING_PROFILES_ACTIVE=postgres
    - SPRING_JPA_GENERATE-DLL=true
    - SPRING_JPA_HIBERNATE_DDL-AUTO=update

  ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
    - ledgers-data:/var/lib/pgsql/data
    expose:
    - 5432
    ports:
    - "5435:5432"
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=ledgers
    - POSTGRESQL_USER=ledgers
    - POSTGRESQL_PASSWORD=ledgers

  xs2a-connector-examples-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a_connector_examples_db
    restart: on-failure
    volumes:
    - xs2a-gateway-data:/var/lib/pgsql/data
    - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
    - 5432
    ports:
    - "5436:5432"
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=consent
    - POSTGRESQL_USER=cms
    - POSTGRESQL_PASSWORD=cms