version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-db-data:

services:
  xs2a-gateway-local-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a_connector_db
    restart: on-failure
    volumes:
    - xs2a-db-data:/var/lib/pgsql/data
    - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
    - 5432
    ports:
    - "5432:5432"    
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=consent
    - POSTGRESQL_USER=cms
    - POSTGRESQL_PASSWORD=cms

 