version: "3"

networks:
  xs2a-net:

volumes:
  consent-management-data:
  ledgers-data:

services:

  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples
    container_name: xs2a-connector-examples
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - LEDGERS_URL=http://ledgers:8088
      - SPRING_PROFILES_ACTIVE=h2,mockspi
      - ASPSP_PROFILE_BASEURL=${ASPSP_PROFILE_BASEURL:-http://aspsp-profile:8080/api/v1}
      - CONSENT_MANAGEMENT_URL=http://consent-management:8080
      - CONSENT-SERVICE_BASEURL=http://consent-management:8080/api/v1
    networks:
      - xs2a-net
    depends_on:
      - aspsp-profile
      - consent-management
      - ledgers

  # ASPSP-PROFILE
  aspsp-profile:
    image: adorsys/xs2a-aspsp-profile
    container_name: aspsp_profile
    restart: on-failure
    environment:
    - JAVA_TOOL_OPTIONS="-Xmx256M"
    - SPRING_PROFILES_ACTIVE=debug_mode
    ports:
    - "48080:8080"
    networks:
    - xs2a-net

  # CONSENT-MANAGEMENT-SYSTEM
  consent-management:
    image: adorsys/xs2a-consent-management
    container_name: consent_management
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
    - JAVA_TOOL_OPTIONS="-Xmx512M"
    - SPRING_DATASOURCE_URL=jdbc:postgresql://consent-management-postgres/consent?currentSchema=consent
    - SPRING_DATASOURCE_USERNAME=cms
    - SPRING_DATASOURCE_PASSWORD=cms
    - ASPSP_PROFILE_BASEURL=${ASPSP_PROFILE_BASEURL:-http://aspsp-profile:8080/api/v1}
    - KEYCLOAK_AUTH_SERVER_URL=http://xs2a-idp:8080/auth
    - KEYCLOAK_CREDENTIALS_SECRET="${XS2A_CMS_CLIENT_SECRET}"
    - SERVER_KEY=ledgers_conenctor_secret
    depends_on:
    - consent-management-postgres

  consent-management-postgres:
    image: centos/postgresql-95-centos7
    container_name: consent_management_postgres
    volumes:
    - consent-management-data:/var/lib/pgsql/data
    - ./consent-management/cms-db-schema/util/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    restart: on-failure
    ports:
    - "5432:5432"
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=consent
    - POSTGRESQL_USER=cms
    - POSTGRESQL_PASSWORD=cms
    expose:
    - 5432

  online-banking-demo-ui:
    image: adorsys/xs2a-mock-online-banking-ui
    container_name: online_banking_demo_ui
    restart: on-failure
    ports:
    - "4200:4200"
    networks:
    - xs2a-net
    environment:
    - XS2A_URL=http://localhost:8080
    - MOCKSERVER_URL=http://localhost:8088
    - ONLINE_BANKING_SERVER_URL=http://localhost:28081
    - CONSENT_MANAGEMENT_URL=http://localhost:38080
    - PROFILE_SERVER_URL=http://localhost:48080
    expose:
    - 4200

  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    networks:
    - xs2a-net
    ports:
    - "8088:8088"
    depends_on:
    - ledgers-db
    environment:
    - DB_HOST=ledgers_db

  ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
    - ledgers-data:/var/lib/pgsql/data
    expose:
    - 5432
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=ledgers
    - POSTGRESQL_USER=ledgers
    - POSTGRESQL_PASSWORD=ledgers