version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:

services:

  aspsp-profile:
    image: adorsys/xs2a-aspsp-profile
    container_name: aspsp_profile
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=debug_mode
    ports:
      - "48080:8080"
    networks:
      - xs2a-net

  xs2a-connector-examples-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a_connector_examples_db
    restart: on-failure
    volumes:
      - xs2a-connector-data:/var/lib/pgsql/data
      - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms

  consent-management:
    image: adorsys/xs2a-consent-management
    container_name: consent_management
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xs2a-connector-examples-db/consent?currentSchema=consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - ASPSP_PROFILE_BASEURL=${ASPSP_PROFILE_BASEURL:-http://aspsp-profile:8080/api/v1}
      - KEYCLOAK_AUTH_SERVER_URL=http://xs2a-idp:8080/auth
      - KEYCLOAK_CREDENTIALS_SECRET="${XS2A_CMS_CLIENT_SECRET}"
      - SERVER_KEY=ledgers_conenctor_secret
    depends_on:
      - xs2a-connector-examples-db
