version: "3"

networks:
  xs2a-net:

volumes:
  ledgers-xs2a-gateway-data:
  ledgers-data:

services:

  ledgers-xs2a-gateway:
    image: adorsys/ledgers-xs2a-gateway
    container_name: ledgers-xs2a-gateway
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - LEDGERS_URL=http://ledgers:8088
      - SPRING_PROFILES_ACTIVE=postgres,mockspi
      - DB_HOST=ledgers_xs2a_gateway_db
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms
    networks:
      - xs2a-net
    depends_on:
      - ledgers-xs2a-gateway-db
      - ledgers

  online-banking-demo-ui:
    image: adorsys/xs2a-mock-online-banking-ui
    container_name: online_banking_demo_ui
    restart: on-failure
    ports:
    - "4200:4200"
    networks:
    - xs2a-net
    environment:
    - XS2A_URL=http://localhost:8080
    - MOCKSERVER_URL=http://localhost:8088
    - ONLINE_BANKING_SERVER_URL=http://localhost:28081
    - CONSENT_MANAGEMENT_URL=http://localhost:38080
    - PROFILE_SERVER_URL=http://localhost:48080
    expose:
    - 4200

  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    networks:
    - xs2a-net
    ports:
    - "8088:8088"
    depends_on:
    - ledgers-db
    environment:
    - DB_HOST=ledgers_db

  ledgers-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_db
    restart: on-failure
    volumes:
    - ledgers-data:/var/lib/pgsql/data
    expose:
    - 5432
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=ledgers
    - POSTGRESQL_USER=ledgers
    - POSTGRESQL_PASSWORD=ledgers

  ledgers-xs2a-gateway-db:
    image: centos/postgresql-95-centos7
    container_name: ledgers_xs2a_gateway_db
    restart: on-failure
    volumes:
    - ledgers-xs2a-gateway-data:/var/lib/pgsql/data
    expose:
    - 5432
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=consent
    - POSTGRESQL_USER=cms
    - POSTGRESQL_PASSWORD=cms