#
# Copyright 2018-2018 adorsys GmbH & Co KG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8089

# Swagger configuration location.
# Empty string, mean the default setting from xs2a-impl will be used.
xs2a.swagger.psd2.api.location: /psd2-api-1.2-Update-2018-08-18-non-oauth.yaml

spring:
  application.name: ledgers-xs2a-gateway
  # These datasource information are provided for the consent db
  datasource:
    username: ${db.user}
    password: ${db.password}
    url: ${db.url}
  jpa:
    show-sql: true
    properties:
      hibrenate.globally_quoted_identifiers: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson:
    serialization:
      write_dates_as_timestamps: false
      wrap-root-value: true

ledgers.url: http://localhost:8088/

consent.cron.expression: 0 0 1 * * ?
scheduler.pool.size: 30
server_key: test123
# ----------------------------------------------

# number of characters in a json string
application.ais.transaction.max-length: 1000

#LOGGER
logging.level.org.springframework.web: ERROR

license.url: https://github.com/adorsys/xs2a/blob/master/LICENSE.md
springfox.documentation.swagger.v2.path: /swagger.json

skip.ssl.certificate.verification: true

# Profile Service config
bank_profile.path: /bank_profile_mockbank.yml

# ENDPOINTS CORS CONFIGURATION
# Whether credentials are supported. When not set, credentials are not supported.
endpoints:
  cors:
    allow-credentials: false
    # Comma-separated list of origins to allow. '*' allows all origins. When not set, CORS support is disabled.
    allowed-origins: '*'
    # Comma-separated list of headers to include in a response.
    allowed-headers: '*'
    # Comma-separated list of methods to allow. '*' allows all methods. When not set, defaults to GET.
    allowed-methods: DELETE,GET,OPTIONS,PATCH,POST,PUT
    # How long, in seconds, the response from a pre-flight request can be cached by clients
    max-age: 3600

---
spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  # SpringBoot 2.x react to this liquibase proprty
  liquibase:
    enabled: false 
db:
  user: sa
  password: sa
  url: jdbc:h2:./target/xs2adbs/consent;DB_CLOSE_DELAY=-1

# SpringBoot 1.x react to this liquibase proprty
liquibase:
  enabled: false 
---
spring:
  profiles: postgres
  jpa:
    properties:
      hibernate.default_schema: consent
  # SpringBoot 2.x react to this liquibase proprty
  liquibase:
    default-schema: consent
    enabled: true 
    change-log: classpath:/master.xml
db:
  host: localhost
  user: cms
  password: cms
  database: consent
  port: 5432
  url: jdbc:postgresql://${db.host}:${db.port}/${db.database}?currentSchema=consent
  
# SpringBoot 1.x react to this liquibase proprty
liquibase:
  default-schema: consent
  enabled: true 
  change-log: classpath:/master.xml

---
spring:
  profiles: dev

logging.level.org.postgresql: INFO
logging.level.org.hibernate.SQL: WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: WARN
logging.level.org.springframework: INFO

management.endpoints.web.exposure.include: "*"
management.endpoints.web.exposure.exclude: env,beans

